version: "3.8"

services:
  user-service:
    container_name: user-service
    build: ./user-service
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres-dev
      POSTGRES_PORT: 5432
    ports:
      - "3000:3000"

  article-service:
    container_name: article-service
    build: ./article-service
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres-dev
      POSTGRES_PORT: 5432
    ports:
      - "3001:3000"

  postgres:
    container_name: postgres-dev
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
